### ISSUE TITLE
New goals, gamemodes and additional functionality

### ISSUE THREAD

**Issue by TheRealAlph4** [pedroteosousa/HollowKnight.BingoSync#7]
Hello!
The HK bingo community has been pretty active recently, and we've been working on new goals, gamemodes etc.
Currently, all of this is going through [a different mod I made](https://github.com/TheRealAlph4/BingoSyncExtension) that (among other things) allows us to add more goals to your mod.
I was wondering whether you'd be open to the idea of merging the new functionality into BingoSync directly.
I'd love to add everything and make a PR, but I don't want to do that if you're inactive or not interested in merging.

Thank you in advance!
\- Alph4

**Comment by pedroteosousa** [comment]
Hi @TheRealAlph4, that would be awesome, I'm down to merge that. I'm very inactive with this mod, but if you message me on discord I will do my best to answer your questions and take a look at your PRs
